server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: compliance-service
          uri: http://compliance-service:8081
          predicates:
            - Path=/api/compliance/**
        - id: monitoring-service
          uri: http://monitoring-service:8082
          predicates:
            - Path=/api/monitoring/**
        - id: rules-engine
          uri: http://rules-engine:8083
          predicates:
            - Path=/api/rules/**
        - id: auto-remediation-service
          uri: http://auto-remediation-service:8084
          predicates:
            - Path=/api/remediation/**
        - id: integration-service
          uri: http://integration-service:8085
          predicates:
            - Path=/api/integration/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server/.well-known/jwks.json
