server:
  port: 8084
spring:
  application:
    name: auto-remediation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ethicaltrader
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret: replace_with_secure_secret
multiTenant:
  enabled: true
